name: Run Tests with PostgreSQL

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: url_shortener
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Wait for Postgres
        run: |
          until pg_isready -h postgres -p 5432; do
            sleep 1
          done

      - name: Run Tests
        env:
          DB_DSN: "host=postgres user=postgres password=postgres dbname=url_shortener port=5432 sslmode=disable"
        run: go test ./... -v
